[package]
name = "example"
version = "0.1.0"
authors = ["csandu"]
edition = "2018"

[lib]
crate_type = ["staticlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
oxidation = { path = ".." }